title: Abuzer Emre's portfolio
author: Abuzer Emre OSMANOGLU
description: Abuzer E. Osmanoğlu is a freelance developer specializing in user interface/experience and frontend of web and mobile applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base URL of your site, e.g. http://example.com
twitter: "@abuzeremreo"
# Build settings
sass:
    style: compressed
permalink: /portfolio/:title
