title: Abuzer Emre - Portfolio
author: Abuzer Emre OSMANOGLU
description: Abuzer Emre Osmanoğlu's portfolio and information about himself.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
    style: compressed
permalink: /portfolio/:title
